export enum Roles {
  DIRECTOR = 'DIRECTOR',
  SENIOR_ASSISTANT = 'SENIOR_ASSISTANT',
  ADMIN_ASSISTANT = 'ADMIN_ASSISTANT',
  EXECUTIVE_SECRETARY = 'EXECUTIVE_SECRETARY',
  MAIL_ARCHIVES_AGENT = 'MAIL_ARCHIVES_AGENT',
  AGENT = 'AGENT',
  ADMIN = 'ADMIN',
}
